  - name: Execute the command in remote shell;
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name: Execute the command in remote shell;
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: Install the rabbitmq
    ansible.builtin.yum:
      name: rabbitmq-server
      state: installed

  - name: Start service unit is running
    ansible.builtin.systemd:
      name: rabbitmq-server
      state: restarted
      enabled: yes

  - name: Add user to server and assign full access control permission;
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present