 - name: Install Mysql
   ansible.builtin.yum:
     name: mysql
     state: installed

 - name: Load Scheme
   ansible.builtin.shell: mysql -h mysql-dev.ndevops.online -uroot -pRoboShop@1 < /app/schema/{{component}}.sql

