
 - name: Add the user roboshop
   ansible.builtin.user:
     name: roboshop

 - name: Recursively remove directory
   ansible.builtin.file:
     path: /app
     state: absent

 - name: Create a directory
   ansible.builtin.file:
     path: /app
     state: directory

 - name: Unarchive a file with extra options
   ansible.builtin.unarchive:
     src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
     dest: /app
     remote_src: yes



